import { useMemo, useState } from 'react';
import { Search, X } from 'lucide-react';
import { cn } from '@/lib/utils';
import { PRODUCT_CATEGORIES } from '@contracts/types';
import { trpc } from '@/providers/trpc';
import ProductCard from '@/components/ProductCard';
import WishingStar from '@/components/admin/WishingStar';
import CategoryTiles from '@/components/shop/CategoryTiles';
import SortSelect, { SORT_OPTIONS, type SortValue } from '@/components/shop/SortSelect';
import { demoShopProducts, toCardProduct, effectivePrice } from '@/components/shop/shop-utils';
import { useRevealDep } from '@/components/shop/useRevealDep';